//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PseudonymMatching.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PseudonymMatching.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string Form1_btnOpenCsv_Click_Something_went_wrong {
            get {
                return ResourceManager.GetString("Form1_btnOpenCsv_Click_Something_went_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// Be aware that rows start at 0 and if viewed in Excel you need to increase by 1 as Excel is 1 based.
        /// </summary>
        internal static string Form1_btnOpenPseudonymFile_Click_ {
            get {
                return ResourceManager.GetString("Form1_btnOpenPseudonymFile_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A possible pseudonym has been discovered in the original data on row .
        /// </summary>
        internal static string Form1_btnOpenPseudonymFile_Click_A_possible_pseudonym_has_been_discovered_in_the_original_data_on_row_ {
            get {
                return ResourceManager.GetString("Form1_btnOpenPseudonymFile_Click_A_possible_pseudonym_has_been_discovered_in_the_" +
                        "original_data_on_row_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Form1_btnOpenPseudonymFile_Click_Completed {
            get {
                return ResourceManager.GetString("Form1_btnOpenPseudonymFile_Click_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV|*.csv.
        /// </summary>
        internal static string Form1_btnOpenPseudonymFile_Click_CSV___csv {
            get {
                return ResourceManager.GetString("Form1_btnOpenPseudonymFile_Click_CSV___csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File.
        /// </summary>
        internal static string Form1_btnOpenXML_Click_Invalid_File {
            get {
                return ResourceManager.GetString("Form1_btnOpenXML_Click_Invalid_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        internal static string Form1_btnOpenXML_Click_Try_again {
            get {
                return ResourceManager.GetString("Form1_btnOpenXML_Click_Try_again", resourceCulture);
            }
        }
    }
}
